### ISSUE TITLE
Existing BBCode libraries

### ISSUE THREAD

**Issue by thunderer** [VVatashi/BBCode#1]
Hi, I found your library while browsing GitHub, and I'm wondering if you'd be interested in checking out an already existing solution? I wrote my own library a few years ago and now it's one of the fastest and most feature-complete (nesting, UTF, events, etc.) out of all the shortcode / BBCode libraries I was able to find. It's also [one of the most popular](https://packagist.org/packages/thunderer/shortcode/stats) shortcode libraries in PHP ecosystem. I would be grateful if you could use it and tell me what do you think about it.

The repository with complete README is here: https://github.com/thunderer/Shortcode.

**Comment by VVatashi** [comment]
Hello, @thunderer.
My library is not pretending to be feature-complete, it is just perfectly fit for my own projects, and I tries to keep it simple and maintainable. But it also has support for nesting and unicode.
I tried your library and for me it looks not very convenient. For example, it does not seem to have built-in functions for tag parameters validation.
In addition, I [did some basic benchmarking](https://gist.github.com/VVatashi/ba246163f73b803e02ac16068268738a), and for me, in any case, my solution is faster from two to ten times. I also tried your RegexParser, and it is fast, but has unacceptable issues with nesting.

**Comment by thunderer** [comment]
Hi @VVatashi, I didn't expect such great feedback! Just to address your comment:

* you're right that there is no parameter validation, there is a "filter shortcodes" event to remove them from processing or you can return the raw shortcode text from the handler. I'll think more about that though - no one requested such feature yet, but it seems like a neat idea after all,
* your benchmark indeed shows an interesting performance difference, I will definitely find some time to thoroughly read your code and see where it comes from. Part of it could be attributed to the differences in approach, but still, good job! One thing I'm especially interested in after a quick glance is that I don't see any recursive calls where I would expect them. Token joining optimization also looks good,
* `RegexParser` does not have support for nesting because it handles the parsing using a single regex, but I have a plan to write an improved regex-based parser that will extract just the shortcode "fragments" and process them like `RegularParser` would.

BTW I understand that this is your library for your private projects, but do you accept PRs? I could have some ideas in the future, so I'd like to know. Thanks again for your reply and keep up the good work!

**Comment by VVatashi** [comment]
Of course I can accept PR if i like it. Anyway it is probably better to open an issue and discuss the changes before changing anything.

> One thing I'm especially interested in after a quick glance is that I don't see any recursive calls where I would expect them. Token joining optimization also looks good,

Yes, I'm trying to avoid recursion when it is not actually needed.
The main idea of the current implementation is to divide text into segments between tags, and then, in a single pass, calculate styles applied to each segment. I got this idea after several lectures on how word processor programs work. My library is primarily oriented on text markup processing, and this approach seems to work great for this use case.
Then I can reduce segments to a tree and generate a valid HTML or something else from it. I do not really like my current implementation of building a tree, maybe something similar to the breadth-first traversal should work better, I should think about it.
